from tkinter import *
window=Tk()
window.title("GUI")
'''top=Frame(window).pack()
bottom=Frame(window).pack(side='bottom')
label=Label(window,text="Welcome").pack()
button=Button(top,text="Button1",width=25,fg='grey',command=window.destroy)
button.pack()
button=Button(top,text="Buton2",width=25,fg='red',command=window.destroy)
button.pack()
button=Button(top,text="Button3",width=25,fg='blue',command=window.destroy)
button.pack()
button=Button(top,text="Button4",width=25,fg='green',command=window.destroy)
button.pack()
'''
check1=IntVar()
check2=IntVar()
check_button1=Checkbutton(window,text="Machine Learning",variable=check1,onvalue=1,offvalue=0).grid(row=0,sticky=W)
check_button2=Checkbutton(window,text="Deep Learning",variable=check2,onvalue=0,offvalue=1).grid(row=1,sticky=W)
window.mainloop()
